import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Chat from '@/Components/Chat'
import Providers from '@/Components/Providers'
import Image from 'next/image'
import bg from "./assests/bg.png"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Providers>

      <body className={inter.className}>
        <div className='max-h-screen min-w-full -z-10'>
        <Image src={bg} layout='fill' quality={100} alt='Background Image' className='opacity-50 object-fit'/>
        </div>
        <Chat/>
        {children}</body>
      </Providers>
    </html>
  )
}
